app/__init__.py
#!/usr/bin/python3
# -*- coding: utf-8 -*-
from flask import Flask
from flask_uploads import UploadSet, configure_uploads, IMAGES, patch_request_class

def createApp(config):
    app = Flask(__name__)
    app.config['SECRET_KEY'] = config.SECRET_KEY
    app.config['UPLOADED_PHOTOS_DEST'] = config.ROOT_PATH + '/app/static/images' # 图像上传到的路径
    
    photos = UploadSet('photos', IMAGES)
    configure_uploads(app, photos)
    patch_request_class(app) 
    
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    return app

app/main/__init__.py
#!/usr/bin/python3
# -*- coding: utf-8 -*-
from flask import Blueprint
main = Blueprint('main', __name__)
# 定义main blueprint对象，便于在views.py文件中应用，替代Flask对象
from . import views

__all__ = ['fileManage', 'perspect', 'views']

app/main/views.py
#!/usr/bin/python3
# -*- coding: utf-8 -*-
from flask import Flask, render_template, session
from flask_uploads import UploadSet, IMAGES
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Regexp

from . import main
from .fileManage import findImgFiles, deleteImgFiles
from .perspect import coordInputToPoint, getMatrix, doPerspectTransform, invMatTocTypeStr, sizeInputToPoint

photos = UploadSet('photos', IMAGES)
class UploadForm(FlaskForm):
    """上传图像文件的表单"""
    photo = FileField(validators=[
        FileAllowed(photos, u'只能上传图片！'), 
        FileRequired(u'文件未选择！')])
    submit = SubmitField(u'上传')

class DoPerspectForm(FlaskForm):
    """上传坐标并进行透视变换的表单"""
    srcImgCoord = StringField(u'选定的原图像坐标:',validators=[DataRequired(message=u"坐标不能为空"),
                                                       Regexp(r'^\s*\(\s*\-?\d+\s*\,\s*\-?\d+\s*\)\s*\;\s*'+
                                                              r'\s*\(\s*\-?\d+\s*\,\s*\-?\d+\s*\)\s*\;\s*'+
                                                              r'\s*\(\s*\-?\d+\s*\,\s*\-?\d+\s*\)\s*\;\s*'+
                                                              r'\s*\(\s*\-?\d+\s*\,\s*\-?\d+\s*\)\s*$', flags=0, message=u"输入不合法")])
    dstImgCoord = StringField(u'选定的目标图像坐标:',validators=[DataRequired(message=u"坐标不能为空"),
                                                       Regexp(r'^\s*\(\s*\-?\d+\s*\,\s*\-?\d+\s*\)\s*\;\s*'+
                                                              r'\s*\(\s*\-?\d+\s*\,\s*\-?\d+\s*\)\s*\;\s*'+
                                                              r'\s*\(\s*\-?\d+\s*\,\s*\-?\d+\s*\)\s*\;\s*'+
                                                              r'\s*\(\s*\-?\d+\s*\,\s*\-?\d+\s*\)\s*$', flags=0, message=u"输入不合法")])
    rstImgSize = StringField(u'设定目标图像大小(列,行):',validators=[DataRequired(message=u"不能为空"),
                                                        Regexp(r'^\s*\(\s*\d+\s*\,\s*\d+\s*\)\s*',
                                                               flags=0,message=u"输入不合法")])
    submit = SubmitField(u'运行透视变换')

@main.route('/', methods=['GET', 'POST'])
def index():
    uploadForm = UploadForm()
    doPerspectForm = DoPerspectForm()

    return render_template('index.html', uploadForm=uploadForm, doPerspectForm=doPerspectForm)

@main.route('/upload', methods=['POST'])
def upload():
    uploadForm = UploadForm()
    doPerspectForm = DoPerspectForm()

    if uploadForm.validate_on_submit():
        # extName = getExtName(uploadForm.photo.data.filename)
        # uploadForm.photo.data.filename = 'src_userInput' + extName

        localImgFiles = findImgFiles("./app/static/images")
        for f in localImgFiles:
            deleteImgFiles("./app/static/images/" + f)

        fileName = photos.save(uploadForm.photo.data)
        fileUrl = photos.url(fileName)
        session['fileUrl'] = fileUrl

    else:
        fileUrl = None

    return render_template('index.html', uploadForm=uploadForm,
                            doPerspectForm=doPerspectForm, fileUrl=repr(session.get('fileUrl')))

@main.route('/doPerspect', methods=['GET', 'POST'])
def doPerspect():
    uploadForm = UploadForm()
    doPerspectForm = DoPerspectForm()

    cTypeStr = ""
    rstImgUrl = ""
    if doPerspectForm.validate_on_submit():
        transMat, invMat = getMatrix(coordInputToPoint(doPerspectForm.srcImgCoord.data),
                             coordInputToPoint(doPerspectForm.dstImgCoord.data))
        cTypeStr = invMatTocTypeStr(invMat)
        size = sizeInputToPoint(doPerspectForm.rstImgSize.data)

        localImgFiles = findImgFiles("./app/static/images")
        if localImgFiles:

            rstImgUrl = doPerspectTransform("./app/static/images/" + localImgFiles[0], transMat, size)
            # print(rstImgUrl)

    return render_template('index.html', uploadForm=uploadForm,
                            doPerspectForm=doPerspectForm, fileUrl=repr(session.get('fileUrl')),
                           cTypeStr = cTypeStr, rstImgUrl=rstImgUrl)

@main.route('/tutorial')
def tutorial():
    return render_template('tutorial.html') 

app/templates/base.html
<html> 
<head>  
<meta http-equiv="content-Type" content="text/html; charset=utf-8">
<title>透视变换矩阵计算</title>
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='default.css')}}">
<! script type="text/javascript" src="{{url_for('static', filename='cnvs.js')}}"><! /script>
</head>

<body>
<header>
<h1>透视变换矩阵计算</h1>
</header>

<nav>
<a href="/">运行</a>
<br/>
<a href="tutorial">教程</a>
<br/>
</nav>

<section>
上传原图像:
<br/>
<! input type="file" name = "inputFile" id = "inputFileId" accept="image/*" />     
<! button  type = "submit" name = "inputFileButton" value = "提交" id = "inputFileButtonId" onclick="inputFileButtonChecked()" />提交<!/button>

<form method="POST" enctype="multipart/form-data">
     {{ form.hidden_tag() }}
     {{ form.photo }}
     {% for error in form.photo.errors %}
         <span style="color: red;">{{ error }}</span>
     {% endfor %}
     {{ form.submit }}
</form>

<canvas id="srcImageCanvas" width="260" height="130">
你的浏览器不支持canvas,请换用firefox或chrome.
</canvas>

{% if fileUrl %}
<script>
var c = document.getElementById("srcImageCanvas"); 
var cxt = c.getContext("2d");
var img = new Image();

img.onload = function()
{
  cxt.drawImage(img,0,0);
}
img.src = {{ fileUrl|safe }}; 
</script>
{% endif %}

</br>
目标图像:
</br>
<canvas id="dstImageCanvas" width="260" height="130">
你的浏览器不支持canvas,请换用firefox或chrome.
</canvas>


</br>
目标图像结果:
</br>
<canvas id="rstImageCanvas" width="260" height="130" >
你的浏览器不支持canvas,请换用firefox或chrome.
</canvas>
</section>

<footer>
墨羽VGC
</footer>

</body>
</html>

app/templates/index.html
<html> 
<head>  
<meta http-equiv="content-Type" content="text/html; charset=utf-8">

<META HTTP-EQUIV="Pragma" CONTENT="no-cache">
<META HTTP-EQUIV="Cache-Control" CONTENT="no-cache">
<META HTTP-EQUIV="Expires" CONTENT="0">

<title>透视变换矩阵计算</title>
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='default.css')}}">
<script type="text/javascript" src="{{url_for('static', filename='cnvs.js')}}"></script>
<script>
    function cnvsReload(cnvsId)
    {
        var imageC = document.getElementById(cnvsId);
        var imageCxt = imageC.getContext("2d");
        if(cnvsId === "srcImageCanvas")
        {
            var img = new Image();
            img.src = {{ fileUrl|safe }};
            imageCxt.drawImage(img, 0, 0);
        }
        else if(cnvsId === "dstImageCanvas")
        {
            imageCxt.fillStyle="#000000";
            imageCxt.fillRect(0, 0, imageCxt.canvas.width, imageCxt.canvas.height);
        }
    }
</script>
</head>

<body>
<header>
    <h1>透视变换矩阵计算</h1>
</header>

<nav>
    <a href="/">运行</a>
    <br/>
    <a href="tutorial">教程</a>
    <br/>
</nav>

<section>
    上传原图像:
    <br/>
    <form action="{{ url_for('main.upload') }}" method="POST" enctype="multipart/form-data">
        {{ uploadForm.hidden_tag() }}
        {{ uploadForm.photo }}
        {% for error in uploadForm.photo.errors %}
            <span style="color: red;">{{ error }}</span>
        {% endfor %}
        {{ uploadForm.submit(onclick="")}}
    </form>

    <canvas id="srcImageCanvas" width="188" height="120"
            onmousemove="cnvsMouseMove(event, this.id, 'srcImgCoordSlideText')"
            onclick="cnvsClick(event, this.id, 'srcImgCoordIndex', 'srcImgCoordInput'), cnvsReload(this.id), cnvsDraw(this.id)">
    你的浏览器不支持canvas,请换用firefox或chrome.
    </canvas>

    <p id="srcImgCoordSlideText"></p>

    <span>当前选中第</span>
    <select id="srcImgCoordIndex">
        <option>0</option>
        <option>1</option>
        <option>2</option>
        <option>3</option>
    </select>
    <span>个坐标</span>


    <hr/>
    目标图像:
    <br/>
    <canvas id="dstImageCanvas" width="188" height="120"
            onmousemove="cnvsMouseMove(event, this.id, 'dstImgCoordSlideText')"
            onclick="cnvsClick(event, this.id, 'dstImgCoordIndex', 'dstImgCoordInput'), cnvsReload(this.id), cnvsDraw(this.id)">
    你的浏览器不支持canvas,请换用firefox或chrome.
    </canvas>

    <p id="dstImgCoordSlideText"></p>

    <span>当前选中第</span>
    <select id="dstImgCoordIndex">
        <option>0</option>
        <option>1</option>
        <option>2</option>
        <option>3</option>
    </select>
    <span>个坐标</span>
</section>

<section>
    <form action="{{ url_for('main.doPerspect') }}" method="POST">
        {{ doPerspectForm.hidden_tag() }}
        {{ doPerspectForm.srcImgCoord.label }}
        <span>&nbsp;&nbsp;</span>
        {{ doPerspectForm.srcImgCoord(id='srcImgCoordInput', size=50) }}
        {% for error in doPerspectForm.srcImgCoord.errors %}
            <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <br/>
        {{ doPerspectForm.dstImgCoord.label }}
        {{ doPerspectForm.dstImgCoord(id='dstImgCoordInput', size=50) }}
        {% for error in doPerspectForm.dstImgCoord.errors %}
            <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <br/>
        {{ doPerspectForm.rstImgSize.label }}
        {{ doPerspectForm.rstImgSize(id='rstImgSizeInput', size=30) }}
        {% for error in doPerspectForm.rstImgSize.errors %}
            <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <br/>
        {{ doPerspectForm.submit }}
    </form>

    <hr/>
    目标图像结果:
    <br/>
    <canvas id="rstImageCanvas" width="188" height="120">
    你的浏览器不支持canvas,请换用firefox或chrome.
    </canvas>

    <hr/>
    矩阵:
    <br/>
    <textarea rows="10" cols="30">{{ cTypeStr }}
    </textarea>

</section>

{% if fileUrl %}
    <script>
        function cnvsLoad()
        {
            var srcImageC = document.getElementById("srcImageCanvas");
            var dstImageC = document.getElementById("dstImageCanvas");
            var rstImageC = document.getElementById("rstImageCanvas");

            var srcImageCxt = srcImageC.getContext("2d");
            var srcImg = new Image();
            srcImg.onload = function()
            {
                srcImageC.setAttribute("width", srcImg.naturalWidth);
                srcImageC.setAttribute("height", srcImg.naturalHeight);
                dstImageC.setAttribute("width", srcImg.naturalWidth);
                dstImageC.setAttribute("height", srcImg.naturalHeight);
                rstImageC.setAttribute("width", srcImg.naturalWidth);
                rstImageC.setAttribute("height", srcImg.naturalHeight);
                srcImageCxt.drawImage(srcImg,0,0);

                coordInputToCoordXY("srcImgCoordInput");
                coordInputToCoordXY("dstImgCoordInput");
                cnvsDraw("srcImageCanvas");
                cnvsDraw("dstImageCanvas");
            };
            srcImg.src = {{ fileUrl|safe }};
        }
        cnvsLoad();
    </script>
{% endif %}

{% if rstImgUrl %}
    <script>
        var rstImageC = document.getElementById("rstImageCanvas");
        var rstImageCxt = rstImageC.getContext("2d");
        var rstImg = new Image();
        rstImg.onload = function()
        {
            rstImageC.setAttribute("width", rstImg.naturalWidth);
            rstImageC.setAttribute("height", rstImg.naturalHeight);
            rstImageCxt.drawImage(rstImg,0,0);
        };
        rstImg.src = "{{url_for('static', filename='images/'+ rstImgUrl|safe )}}"
    </script>
{% endif %}

<footer>
    <a href="https://github.com/voaignidc" target="_blank">墨羽VGC</a>
</footer>

</body>
</html>

app/templates/tutorial.html
<html>  
<head>  
<meta http-equiv="content-Type" content="text/html; charset=utf-8">
<title>使用教程</title>
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='default.css')}}">
</head>
<body>
<header>
    <h1>使用教程</h1>
</header>

<nav>
    <a href="/">运行</a>
    <br/>
    <a href="tutorial">教程</a>
    <br/>
</nav>

<section>
教程还没写
</section>


<footer>
    <a href="https://github.com/voaignidc" target="_blank">墨羽VGC</a>
</footer>

</body>
</html>